name: DevOps Pipeline

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo "Build done"

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - run: echo "Test done"
